### ISSUE TITLE
Update props

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/furl#2]
- [x] Add prop for autolinking in applicable elements such as `<Text>` ~~and `<Paragraph>`~~
- [x] Add `...rest` to all existing components `props`
- [x] Use forward refs whenever possible
- [x] Check [HTMLreference](https://htmlreference.io/) for component-specific props
- [x] Add `style` props to all components
- [x] Check all applicable `props` for React and add custom checking for each one if/as necessary
- [x] Add generic `props` for most components with text (`fontFamily`, `fontSize`, `fontWeight`)
- [x] Add generic `props` for most components with color and background color (`foreColor`, `backColor`)
- [x] Add generic `props` for most components for padding and margins, if possible

**Comment by Chalarangelo** [comment]
**TODO**: Check usage of `..rest` and if it should always apply to top-level DOM element. Evaluate for all components.

**Comment by Chalarangelo** [comment]
**CHECK: ** `forwardRef` has only been used in the components where it is absolutely necessary as to not overcomplicate the API.

**Comment by Chalarangelo** [comment]
- **CHECK**: Nothing left over in HTMLReference.
- **CHECK**: `style` is part of `...rest`, nothing to do there.
